### ISSUE TITLE
Q: How to parse runtime strings when using derive?

### ISSUE THREAD

**Issue by Dietr1ch** [dxshie/kv3#1]
I feel there must be something about lifetimes that I don't understand properly and I can't figure out how to parse a runtime string using the derive feature.

It seems that calling `serde_kv3(text: &str)` forces any `&str` to have `'static` lifetime, but runtime strings can't have that[^0]

---

I tried reducing my error here,

```rust
use kv3::kv3_serde::serde_kv3;

#[derive(Debug, Default, PartialEq, Deserialize, Serialize)]
struct Foo<'de> {
    huge_string: &'de str,  // Using `String` didn't help me either :/
    // More stuff..
}

enum FooError {
    ParseError,
}

// Using a static function because trying to implement `TryFrom<&str>` brings in new lifetime annotations that so far only make things more confusing.
pub fn foo_from_str<'de>(foo_str: &'de str) -> Result<Foo<'de>, FooError> {
    serde_kv3::<'de>(foo_str).map_err(|_| FooError::ParseError)
    //?         ^ Why isn't this lifetime used?
    //?         error[E0521]: borrowed data escapes outside of function
}

fn main() {
    let text: String = fs::read_to_string("path/to/file.txt")?
        .expect("Should have been able to read the file");
        
    let foo = foo_from_str(&text)?;  // References in `foo` could be backed by `text` until the end of the scope.
    println!("{:#?}", foo);
}
```

I tried the simple way too of letting `rustc` figure out lifetimes for me, but it tells me it must be static too,

```rust
pub fn simple_foo_from_str(foo_str: &str) -> Result<Foo, FooError> {
    //?                    -------  - let's call the lifetime of this reference `'1`
    //?                               `foo_str` is a reference that is only valid in the function body
    
    serde_kv3(foo_str).map_err(|_| FooError::ParseError)
    //? ^^^^^ ^^^^^^^
    //?  |
    //?  `foo_str` escapes the function body here
    //?   argument requires that `'1` must outlive `'static`
}
```

So far [non-derive examples](https://docs.rs/kv3/latest/kv3/#example) work on static and non-static strings, but I can't get the [derive example](https://docs.rs/kv3/latest/kv3/kv3_serde/fn.serde_kv3.html#example) to work with `String` either :/

[^0]: Unless you workaround this with [`LazyLock`](https://doc.rust-lang.org/std/sync/struct.LazyLock.html), but it's not a great solution.

**Comment by dxshie** [comment]
the `'static` is not really warrented at that point i removed that already
this is fixed in master https://github.com/dxshie/kv3/commit/984d1ad22bbfc190212d8f763dc93ba9c0913ecc i just didn't bother doing a release of the current commit if you wanna use the creats.io verison do the workaround below

workaround when using crates.io crate version 0.1.1

```rust
let my_string = String::from("Hi i'm a heap growable string");
let static_str: &'static str = Box::leak(my_string.into_boxed_str());
```

or use the git repo which does not require a static lifetime (which is probably fine but i might someday introduce breaking changes)
`kv3 = { git ="https://github.com/dxshie/kv3" }`

ps: sorry for the late answer / please close the issue if your issue has been resolved and it works

**Comment by Dietr1ch** [comment]
Thanks for the quick reply!

I'll just track the git repo.

**Comment by dxshie** [comment]
@Dietr1ch i just pushed a major change so you might see issues on compilation via git repo tracking if not locked
